name: Keep Supabase awake

on:
  schedule:
    - cron: '0 10 * * 1,4'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping cycle app
        run: |
          curl -X GET "https://sdvmycusfyavsuvsjvrv.supabase.co/rest/v1/cycle_data?limit=1" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkdm15Y3VzZnlhdnN1dnNqdnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4Mjc1NjAsImV4cCI6MjA5MjQwMzU2MH0.sOPwil85LdViJ81HD_hFu1SWbQW9M1tEiR25CtcFmaw"

      - name: Ping cloud app
        run: |
          curl -X GET "https://pukzhmhevjbfwvhjzppr.supabase.co/rest/v1/cloud_data?limit=1" \
          -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1a3pobWhldmpiZnd2aGp6cHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc3NjUzNTYsImV4cCI6MjA5MzM0MTM1Nn0.-Jl1tv-xeOTwv6cd-OgF-ovooLfYyzoaA2c7Seax3Zo"
